# Generated by Django 5.2.1 on 2025-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='context',
            field=models.TextField(default='test1'),
            preserve_default=False,
        ),
    ]
